language: java
jdk:
  - openjdk8
  - openjdk13
  - oraclejdk8
  - oraclejdk9
  - oraclejdk13
before_install:
  - pip install --user codecov
after_success:
  - codecov
branches:
  except:
    - appveyor
